"""Generate coach_core.py from the notebook.

The web app must run the SAME code the notebook runs -- not a copy that
slowly drifts out of sync. So instead of retyping the classes here, this
script lifts them straight out of customer_support_coach.ipynb.

Run it again any time you change Part 2 of the notebook:

    python3 app/build_core.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
NOTEBOOK = os.path.join(os.path.dirname(HERE), "customer_support_coach.ipynb")
OUTPUT = os.path.join(HERE, "coach_core.py")


def cell_source(notebook, index):
    return "".join(notebook["cells"][index]["source"])


# Import roots that are not in the standard library.
THIRD_PARTY = {"google", "transformers", "torch", "flask", "numpy"}


def sort_imports(block):
    """Put the extracted import block in isort order.

    The notebook groups its imports for a human reader; the generated module
    is linted in CI, which wants stdlib then third party, each alphabetical.
    Sorting HERE means the notebook stays readable AND the generated file
    stays lint-clean, instead of the two pulling against each other.
    """
    stdlib, third_party = [], []
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        root = line.split()[1].split(".")[0]
        (third_party if root in THIRD_PARTY else stdlib).append(line)

    def key(line):
        parts = line.split()
        # isort puts every plain "import x" before any "from x import y".
        return (line.startswith("from"), parts[1].lower())

    groups = [sorted(set(stdlib), key=key), sorted(set(third_party), key=key)]
    return "\n\n".join("\n".join(g) for g in groups if g)


def slice_between(text, start_marker, end_marker=None):
    """Return the part of `text` from start_marker up to end_marker.

    Passing end_marker=None takes everything to the end of the cell.
    """
    start = text.index(start_marker)
    end = text.index(end_marker) if end_marker else len(text)
    return text[start:end].rstrip() + "\n"


def find_cell(notebook, needle):
    for index, cell in enumerate(notebook["cells"]):
        if needle in "".join(cell["source"]):
            return index
    raise LookupError(f"no cell contains {needle!r}")


def main():
    with open(NOTEBOOK) as handle:
        notebook = json.load(handle)

    setup_cell = find_cell(notebook, "def get_gemini_api_key")
    models_cell = find_cell(notebook, "class ConversationState")
    coach_cell = find_cell(notebook, "class AICoach")

    # suggest_reply() now quotes the real help articles, so the knowledge base
    # has to travel with the engine. It lives in Part 1 of the notebook but
    # needs no models, so it imports cleanly here.
    kb_cell = find_cell(notebook, "KNOWLEDGE_BASE = {")

    key_helpers = slice_between(
        cell_source(notebook, setup_cell),
        "# ---- A helper both Step 2 and Step 20 need ----",
        'print("All libraries installed and imported.")',
    )

    data_models = slice_between(
        cell_source(notebook, models_cell),
        "@dataclass",
        'print("Data models defined.")',
    )

    # Start at the schemas, not at "class AICoach" -- they are defined above
    # the class in the same cell, and the class cannot work without them.
    coach = slice_between(
        cell_source(notebook, coach_cell),
        "# ---- Response schemas ----",
        'print("AICoach defined.")',
    )

    knowledge_base = slice_between(
        cell_source(notebook, kb_cell),
        "KNOWLEDGE_BASE = {",          # to the end of the cell
    )

    # Take the imports from the notebook too, rather than hardcoding a list
    # here. A hardcoded banner silently goes stale the moment the notebook
    # gains an import -- which is exactly how coach_core.py ended up without
    # "import time" and crashed inside the retry path.
    imports = slice_between(
        cell_source(notebook, setup_cell),
        "import os",
        "# ---- A helper both Step 2 and Step 20 need ----",
    )
    imports = sort_imports(imports)

    banner = (
        '"""Coaching engine, generated from customer_support_coach.ipynb.\n\n'
        "DO NOT EDIT THIS FILE BY HAND. Edit the notebook, then run:\n\n"
        "    python3 app/build_core.py\n\n"
        f"Source cells: {setup_cell} (key helper), {kb_cell} (knowledge base), "
        f"{models_cell} (data models), {coach_cell} (AICoach).\n"
        '"""\n\n'
        + imports + "\n\n"
    )

    with open(OUTPUT, "w") as handle:
        handle.write(banner)
        handle.write(key_helpers)
        handle.write("\n\n")
        handle.write(data_models)
        handle.write("\n\n")
        handle.write(knowledge_base)   # must come before AICoach uses it
        handle.write("\n\n")
        handle.write(coach)

    # Guard against the failure above ever coming back: compile the result and
    # check that every global it references is either imported or defined.
    import symtable
    with open(OUTPUT) as handle:
        source = handle.read()
    table = symtable.symtable(source, OUTPUT, "exec")
    defined = {name for name in table.get_identifiers()}
    missing = sorted(
        name
        for child in table.get_children()
        for name in child.get_identifiers()
        if child.lookup(name).is_global()
        and name not in defined
        and name not in dir(__builtins__)
        and not hasattr(__builtins__, name)
    )
    if missing:
        print(f"  WARNING: these names are used but never defined: {missing}")

    with open(OUTPUT) as handle:
        lines = sum(1 for _ in handle)
    print(f"wrote {OUTPUT} ({lines} lines)")
    print(f"  key helper  <- notebook cell {setup_cell}")
    print(f"  knowledge   <- notebook cell {kb_cell}")
    print(f"  data models <- notebook cell {models_cell}")
    print(f"  AICoach     <- notebook cell {coach_cell}")


if __name__ == "__main__":
    main()
