"""Coaching engine, generated from customer_support_coach.ipynb.

DO NOT EDIT THIS FILE BY HAND. Edit the notebook, then run:

    python3 app/build_core.py

Source cells: 1 (key helper), 17 (knowledge base), 26 (data models), 28 (AICoach).
"""

import json
import os
import re
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import List, Optional

from google import genai
from google.genai import types

# ---- A helper both Step 2 and Step 20 need ----
# It lives HERE, in the cell nothing can work without, so it is always defined
# even if you skip Step 2 or jump straight to Part 2 after a kernel restart.

# File names we accept for the key file, tried in this order.
KEY_FILE_NAMES = [
    "gemini_api_key.txt",
    "gemini api key.txt",
    "gemini_key.txt",
    "api_key.txt",
    ".env",
]

# If none of those exact names exist, any .txt file whose name contains these
# word pairs counts too, so a slightly differently named file is still found.
# Matching ignores upper/lower case.
KEY_FILE_WORDS = [("gemini", "key"), ("api", "key")]


def key_file_folders():
    """Every folder we are willing to look in for the key file."""

    folders = []

    def add(folder):
        if folder and os.path.isdir(folder) and folder not in folders:
            folders.append(folder)

    # 1. Wherever this kernel was started, plus a few folders above it. This
    #    is what catches "I started Jupyter from the wrong directory".
    here = os.getcwd()
    add(here)

    parent = here
    for _ in range(3):
        parent = os.path.dirname(parent)
        add(parent)

    # 2. VS Code tells the notebook its own path in this variable, so we can
    #    look next to the .ipynb file itself even if the kernel started
    #    somewhere else entirely.
    notebook_path = globals().get("__vsc_ipynb_file__")
    if notebook_path:
        add(os.path.dirname(notebook_path))

    # 3. Where Colab puts uploaded files, and mounted Google Drive.
    add("/content")
    add("/content/drive/MyDrive")

    # 4. Home and Downloads, for a key file kept outside the project folder.
    home = os.path.expanduser("~")
    add(home)
    add(os.path.join(home, "Downloads"))

    return folders


def find_key_file():
    """Return the path of the first key file we can find, or ""."""

    folders = key_file_folders()

    # Exact names first, in every folder.
    for folder in folders:
        for file_name in KEY_FILE_NAMES:
            path = os.path.join(folder, file_name)
            if os.path.isfile(path):
                return path

    # Then the loose match. We skip home and Downloads here on purpose -- a
    # search that broad could pick up an unrelated file.
    for folder in folders[:4]:

        try:
            entries = sorted(os.listdir(folder))
        except OSError:
            continue          # no permission to read this folder

        for entry in entries:

            lowered = entry.lower()

            if not lowered.endswith(".txt"):
                continue

            for first_word, second_word in KEY_FILE_WORDS:
                if first_word in lowered and second_word in lowered:
                    path = os.path.join(folder, entry)
                    if os.path.isfile(path):
                        return path

    return ""


def read_key_file():
    """Read GEMINI_API_KEY out of a local key file. Returns "" if not found."""

    path = find_key_file()

    if path:

        with open(path) as key_file:
            for line in key_file:

                line = line.strip()

                # Skip blank lines and the "# ..." instructions in the file.
                if not line or line.startswith("#"):
                    continue

                if "=" in line:
                    # A "GEMINI_API_KEY=..." line.
                    name, _, value = line.partition("=")
                    if name.strip() == "GEMINI_API_KEY":
                        value = value.strip().strip("\"'")
                        if value:
                            return value
                else:
                    # A file holding nothing but the key itself.
                    return line.strip("\"'")

    return ""


def get_gemini_api_key(prompt_if_missing=True):
    """Find the Gemini API key. Returns "" if we could not get one.

    Looks in four places, in order, and remembers whatever it finds so the
    rest of the notebook can just read the environment variable.
    """

    # 1. Already in the environment? Then we are done.
    key = os.getenv("GEMINI_API_KEY", "").strip()

    # 2. A key file next to the notebook -- the easiest option, because you
    #    edit it once and never see a prompt again.
    if not key:
        key = read_key_file()

    # 3. On Colab: the Secrets panel (key icon in the left sidebar). Add a
    #    secret named GEMINI_API_KEY and switch "Notebook access" on.
    if not key:
        try:
            from google.colab import userdata
            key = (userdata.get("GEMINI_API_KEY") or "").strip()
        except Exception:
            key = ""

    # 4. Otherwise, type it in. getpass hides what you type, so the key never
    #    appears in the notebook output.
    #    HEADS UP: in VS Code the input box appears at the TOP of the window,
    #    not next to the cell. It is easy to miss and dismiss by accident.
    if not key and prompt_if_missing:
        from getpass import getpass
        key = getpass("Paste your Gemini API key: ").strip()

    if key:
        os.environ["GEMINI_API_KEY"] = key

    return key


@dataclass
class Message:
    """Represents one message in the conversation."""
    speaker: str
    text: str


@dataclass
class ConversationState:
    """Stores the complete conversation and current customer risk."""
    history: List[Message] = field(default_factory=list)
    sentiment: str = "unknown"
    urgency: str = "unknown"
    escalation_risk: str = "unknown"
    frustration: int = 0          # 0-100, judged across the whole conversation
    trend: str = "unknown"        # rising / falling / flat
    key_issue: str = ""

    def add_message(self, speaker: str, text: str):
        """Add a new message to the conversation history."""
        self.history.append(
            Message(
                speaker=speaker,
                text=text
            )
        )


@dataclass
class CoachingFeedback:
    """Stores feedback about the agent's response."""
    tone_score: int
    empathy_score: int
    clarity_score: int
    coaching_tip: str


KNOWLEDGE_BASE = {
    "refund":
        "Refund requests are sent back to your original payment method within "
        "5-7 working days. If money or paise was deducted but the purchase failed, "
        "the amount is reversed automatically. Check Orders > Refund Status to "
        "track a pending refund or cancelled payment.",

    "recharge":
        "If a mobile recharge or prepaid plan fails but money was deducted, the "
        "operator reverses the amount within 24 hours. Keep your transaction ID "
        "and recharge number handy. Do not retry the same recharge again, or you "
        "may be charged twice.",

    "delivery":
        "Standard delivery of an order takes 3-5 working days. Track your parcel "
        "under My Orders > Track Shipment. If the courier marks the package "
        "delivered but it has not arrived, raise a claim within 48 hours.",

    "network":
        "If your internet is not working, the network is slow, or there is no "
        "signal, restart the router, check for an outage in your area, and "
        "reinsert the SIM. If the connection speed is still poor we can run a "
        "line test on your line.",

    "account":
        "To reset a forgotten password use Forgot Password on the login screen. "
        "To change your registered email, mobile number or address, open "
        "Profile > Edit Details and verify the OTP we send you.",
}

# Words so common that they appear in almost every sentence. If we counted them
# they would make every article look like a match, so we ignore them.
STOPWORDS = {
    "i", "me", "my", "we", "our", "you", "your", "it", "its", "this", "that",
    "the", "a", "an", "is", "are", "was", "were", "be", "been", "am", "do",
    "does", "did", "have", "has", "had", "can", "could", "will", "would",
    "to", "for", "of", "and", "or", "but", "in", "on", "at", "from", "with",
    "not", "no", "if", "so", "very", "much", "get", "got", "please", "hi",
    "hello", "there", "what", "when", "why", "how", "still", "any", "all",
}

# How many points a message needs before we trust the match.
#
# Why 1 and not something stricter? Hinglish messages are SHORT on English
# words. "bhai order abhi tak nahi aaya" contains exactly one word our English
# articles can match on -- "order" -- so any threshold above 1 would throw away
# a perfectly clear delivery complaint. With a bigger knowledge base you would
# raise this number, and the returned "score" tells you how strong the match
# actually was (1 = weak, 4+ = confident).
MIN_MATCH_SCORE = 1


def message_to_words(text):
    """Lowercase the text, remove punctuation, and return the meaningful words."""
    cleaned = text.lower()

    # Same punctuation trick as Step 10, so "refund." becomes "refund".
    for punctuation in ",.!?;:()>\"'":
        cleaned = cleaned.replace(punctuation, " ")

    # Keep only the words that actually carry meaning.
    return [word for word in cleaned.split() if word not in STOPWORDS]


def keyword_kb_article(customer_message):
    """Find the best matching help article by WORD OVERLAP.

    This was the only matcher until Step 14 gained semantic search below. It
    is kept as the fallback, because it needs no API key, no network and no
    quota -- when embeddings are unavailable, this still works.

    Returns {"topic", "article", "score", "how"}, or None.
    """
    # A set, so repeated words are only counted once.
    customer_words = set(message_to_words(customer_message))

    best_topic = None
    best_score = 0

    # Compare the message against every article and keep the strongest match.
    for topic, article in KNOWLEDGE_BASE.items():
        article_words = set(message_to_words(article))

        # "&" gives the words the two sets SHARE. More shared words = better fit.
        score = len(customer_words & article_words)

        # The topic name is a far stronger clue than any ordinary word, so a
        # direct mention of "refund" or "recharge" earns bonus points.
        if topic in customer_words:
            score += 3

        # NOTE: ">" not ">=", so on a tie the topic listed EARLIER in the
        # dictionary wins. That is why each article should own its distinctive
        # words -- "order" lives in the delivery article only, so a message that
        # just says "order" is not accidentally answered with a refund policy.
        if score > best_score:
            best_score = score
            best_topic = topic

    # If nothing shared even one meaningful word, we would rather admit we do
    # not know than have the agent read out an article about the wrong topic.
    if best_topic is None or best_score < MIN_MATCH_SCORE:
        return None

    return {"topic": best_topic,
            "article": KNOWLEDGE_BASE[best_topic],
            "score": best_score,
            "how": "keyword"}


# ==========================================================================
# Semantic search -- matching on MEANING instead of shared words
# ==========================================================================
#
# Word overlap only finds an article when the customer happens to use our
# vocabulary. "kab tak paisa wapas milega" is a refund question that shares
# not one word with the refund article, so the keyword matcher returned
# nothing. Embeddings turn both the question and the article into vectors
# whose direction encodes meaning, so the two can be compared directly.

EMBED_MODEL = os.getenv("GEMINI_EMBED_MODEL", "gemini-embedding-001")

# How close a match must be before we trust it.
#
# Measured, not guessed: across 8 real paraphrases and 4 questions the
# knowledge base genuinely cannot answer, correct matches scored 0.596-0.711
# and the unanswerable ones never got above 0.559. 0.58 sits in that gap,
# leaning towards precision -- quoting the WRONG article at a customer is
# worse than admitting we have nothing.
SEMANTIC_THRESHOLD = 0.58

_embed_client = None      # built once, on first use
_kb_vectors = None        # the articles, embedded once and kept


def _embedder():
    """The Gemini client used only for embeddings."""
    global _embed_client
    if _embed_client is None:
        key = get_gemini_api_key(prompt_if_missing=False)
        if not key:
            raise RuntimeError("No API key, so semantic search is unavailable.")
        _embed_client = genai.Client(api_key=key)
    return _embed_client


def embed(texts):
    """Turn a list of strings into a list of vectors, in ONE API call."""
    response = _embedder().models.embed_content(
        model=EMBED_MODEL,
        contents=list(texts),
    )
    return [item.values for item in response.embeddings]


def kb_vectors():
    """Embed every help article once, then keep the result in memory.

    The articles do not change while the notebook runs, so re-embedding them
    for every question would be pure waste -- and on a free tier, quota you
    cannot spare. Five articles cost exactly one API call, ever.
    """
    global _kb_vectors
    if _kb_vectors is None:
        topics = list(KNOWLEDGE_BASE)
        # Embed "topic: article" so the topic word carries weight too.
        _kb_vectors = dict(zip(
            topics,
            embed(f"{topic}: {KNOWLEDGE_BASE[topic]}" for topic in topics),
        ))
    return _kb_vectors


def cosine(first, second):
    """How closely two vectors point in the same direction, from -1 to 1."""
    dot = sum(a * b for a, b in zip(first, second))
    size_first = sum(a * a for a in first) ** 0.5
    size_second = sum(b * b for b in second) ** 0.5

    if not size_first or not size_second:
        return 0.0

    return dot / (size_first * size_second)


def semantic_kb_article(customer_message):
    """Best article by MEANING, or None if nothing is close enough."""
    vectors = kb_vectors()

    # The customer's message goes to the embeddings API too, which is just as
    # much a third party as the chat model. Clean it first. Nothing needs
    # restoring here -- we only ever use the resulting vector.
    question = embed([Redactor().redact(customer_message)])[0]

    best_topic, best_score = None, -1.0

    for topic, vector in vectors.items():
        score = cosine(question, vector)
        if score > best_score:
            best_topic, best_score = topic, score

    if best_score < SEMANTIC_THRESHOLD:
        return None          # we would rather say nothing than guess

    return {"topic": best_topic,
            "article": KNOWLEDGE_BASE[best_topic],
            "score": round(best_score, 3),
            "how": "semantic"}


def find_kb_article(customer_message):
    """The best help article for this message.

    Semantic search first, because it understands paraphrase and Hinglish.
    Keyword matching is the safety net -- used when embeddings are
    unavailable (no key, no network, quota gone) and as a second opinion when
    semantic search comes up empty.
    """
    try:
        match = semantic_kb_article(customer_message)
        if match:
            return match
    except Exception:
        pass          # any embedding problem simply falls through

    return keyword_kb_article(customer_message)


# Every unanswered question gets stored here so the team can review them later.
KNOWLEDGE_GAP_LOG = []


def knowledge_gap_detector(customer_message):
    """Return True if the knowledge base cannot answer this, and log the question.

    A knowledge gap is not a bug -- it is a to-do list. Each logged question is
    a help article that somebody still needs to write.
    """
    match = find_kb_article(customer_message)

    if match is None:
        KNOWLEDGE_GAP_LOG.append(customer_message)
        return True

    return False


# ---- Response schemas ----
#
# These are handed to the API with each request. The model is then physically
# unable to return prose, a markdown code fence, a missing field, or a word
# outside an enum -- the API rejects it before we ever see it. The "enum" and
# "description" entries do real work: the model reads the descriptions, and
# the enums make the sentiment/urgency/trend values self-validating.

ANALYSIS_SCHEMA = {
    "type": "object",
    "properties": {
        "sentiment": {
            "type": "string", "enum": ["positive", "neutral", "negative"],
            "description": "How the customer sounds in their latest message.",
        },
        "urgency": {
            "type": "string", "enum": ["low", "medium", "high"],
            "description": "How quickly this needs an answer.",
        },
        "escalation_risk": {
            "type": "string", "enum": ["low", "medium", "high"],
            "description": "Chance this becomes a complaint or a cancellation.",
        },
        "frustration": {
            "type": "integer",
            "description": "How frustrated the customer is now, from 0 to 100.",
        },
        "trend": {
            "type": "string", "enum": ["rising", "falling", "flat"],
            "description": "Direction of frustration compared with earlier turns.",
        },
        "key_issue": {
            "type": "string",
            "description": "Short description of the customer's main problem.",
        },
    },
    "required": ["sentiment", "urgency", "escalation_risk",
                 "frustration", "trend", "key_issue"],
}

SCORECARD_SCHEMA = {
    "type": "object",
    "properties": {
        "tone_score": {"type": "integer", "description": "Tone, 1 to 10."},
        "empathy_score": {"type": "integer", "description": "Empathy, 1 to 10."},
        "clarity_score": {"type": "integer", "description": "Clarity, 1 to 10."},
        "coaching_tip": {
            "type": "string",
            "description": "One sentence naming the specific change to make.",
        },
    },
    "required": ["tone_score", "empathy_score", "clarity_score", "coaching_tip"],
}

REPLY_SCHEMA = {
    "type": "object",
    "properties": {
        "reply": {
            "type": "string",
            "description": "The reply text the agent should send, and nothing else.",
        },
    },
    "required": ["reply"],
}


# ==========================================================================
# Keeping personal details away from the model
# ==========================================================================
#
# Every customer message we send to Gemini leaves this machine and lands on
# somebody else's servers. A support chat is full of things that should not
# make that trip: phone numbers, email addresses, card numbers.
#
# So we swap them for placeholders on the way OUT, and put the real values
# back on the way IN. The model reasons about "[PHONE_1]" and never learns
# the number; the customer still reads their own details in the reply.
#
# Order ids get the same treatment, with one wrinkle handled in gather_facts():
# a tool call needs the REAL id to look anything up, so the placeholder is
# swapped back just before the function runs -- inside our own process.

REDACTION_PATTERNS = [
    # Order matters. Emails contain digits, so they must be taken out before
    # anything goes looking for numbers.
    ("EMAIL", re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")),
    ("CARD",  re.compile(r"\b(?:\d[ -]?){12,18}\d\b")),
    ("ORDER", re.compile(r"\b(?:OD|RF|ORD|INV)[-_]?\d{3,8}\b", re.IGNORECASE)),
    ("PHONE", re.compile(
        r"(?:\+\d{1,3}[\s-]?)?\b\d{5}[\s-]?\d{5}\b"      # +91 98765 43210
        r"|\b\d{10}\b"                                     # 9876543210
    )),
]


def mask(value):
    """A hint of the original, for our own logs. Never the whole thing."""
    text = str(value)
    if "@" in text:
        name, _, domain = text.partition("@")
        return (name[:2] + "***@" + domain) if len(name) > 2 else "***@" + domain
    if len(text) <= 4:
        return "*" * len(text)
    return text[:2] + "*" * (len(text) - 4) + text[-2:]


class Redactor:
    """Swaps personal details for placeholders, and back again.

    One instance per conversation, so the same phone number keeps the same
    placeholder from turn to turn -- otherwise the model would think it was
    looking at two different people.
    """

    def __init__(self):
        self.to_real = {}      # "[PHONE_1]" -> "+91 98765 43210"
        self.to_token = {}     # "+91 98765 43210" -> "[PHONE_1]"
        self.found = []        # what we took out, for the audit log

    def redact(self, text):
        """Return text with personal details replaced by placeholders."""
        if not text:
            return text

        cleaned = str(text)

        for kind, pattern in REDACTION_PATTERNS:
            # kind is bound as a default argument, not captured from the loop.
            # It is safe either way here -- pattern.sub() runs swap before the
            # next iteration -- but binding it says so, and keeps the linter's
            # late-binding warning meaningful everywhere else.
            def swap(match, kind=kind):
                original = match.group(0)

                # Seen before in this conversation? Reuse its placeholder.
                if original in self.to_token:
                    return self.to_token[original]

                count = sum(1 for f in self.found if f["kind"] == kind) + 1
                token = f"[{kind}_{count}]"

                self.to_token[original] = token
                self.to_real[token] = original
                self.found.append({"kind": kind, "placeholder": token,
                                   "masked": mask(original)})
                return token

            cleaned = pattern.sub(swap, cleaned)

        return cleaned

    def restore(self, text):
        """Put the real values back.

        Models do not always echo a placeholder exactly as given -- they drop
        the brackets and write ORDER_1, or lower-case it. Matching only the
        exact form left "Refund for order ORDER_1" in front of a customer, so
        the bare and lower-cased forms are handled too.
        """
        if not text:
            return text

        restored = str(text)

        for token, original in self.to_real.items():
            bare = token.strip("[]")
            for variant in (token, bare, token.lower(), bare.lower()):
                restored = restored.replace(variant, original)

        return restored

    def log(self):
        """What was taken out, for the case record. Masked, not the originals."""
        return list(self.found)


# ==========================================================================
# The back office -- what the coach can actually look up and do
# ==========================================================================
#
# A support tool that only talks is a chatbot. One that can read the order
# system and act on it is an agent. These four functions stand in for that
# system, backed by orders.json.
#
# The model never runs them itself. It asks for a function BY NAME, our code
# decides whether to run it, runs it, and only then does the model see the
# result. That boundary is the whole point: the model can *request* a refund;
# the code decides whether one actually happens.


def orders_path():
    """Find orders.json, reusing the same folder search as the key file."""
    for folder in key_file_folders():
        candidate = os.path.join(folder, "orders.json")
        if os.path.isfile(candidate):
            return candidate
    return ""


def load_orders():
    path = orders_path()
    if not path:
        return {}
    try:
        with open(path) as handle:
            return json.load(handle)
    except (json.JSONDecodeError, OSError):
        return {}


def save_orders(data):
    """Write the mock back office back to disk, atomically."""
    path = orders_path()
    if not path:
        return False
    tmp = path + ".tmp"
    with open(tmp, "w") as handle:
        json.dump(data, handle, indent=1)
    os.replace(tmp, path)
    return True


# ---- the four tools ----

def check_order_status(order_id=None):
    """Look up one order, or list the recent ones if no id was given."""
    data = load_orders()
    orders = data.get("orders", [])

    if not orders:
        return {"error": "The order system is unavailable."}

    if order_id:
        for order in orders:
            if order["order_id"].lower() == str(order_id).lower():
                return order
        return {"error": f"No order {order_id} exists on this account."}

    # The customer rarely quotes an order number, so default to showing
    # what they recently bought rather than demanding one.
    return {"recent_orders": orders[:3]}


def check_refund_status(order_id=None, refund_id=None):
    """Look up a refund by either the refund id or the order it belongs to."""
    data = load_orders()
    refunds = data.get("refunds", [])

    for refund in refunds:
        if refund_id and refund["refund_id"].lower() == str(refund_id).lower():
            return refund
        if order_id and refund["order_id"].lower() == str(order_id).lower():
            return refund

    if order_id or refund_id:
        return {"error": "No refund has been raised for that order yet."}

    return {"refunds": refunds} if refunds else {"error": "No refunds on file."}


def issue_refund(order_id, reason="Requested by customer"):
    """Raise a refund against an order. THIS CHANGES DATA."""
    data = load_orders()
    orders = data.get("orders", [])

    order = next((o for o in orders
                  if o["order_id"].lower() == str(order_id).lower()), None)
    if order is None:
        return {"error": f"No order {order_id} exists on this account."}

    existing = next((r for r in data.get("refunds", [])
                     if r["order_id"].lower() == str(order_id).lower()), None)
    if existing:
        return {"error": "A refund already exists for this order.",
                "refund": existing}

    today = datetime.now()
    refund = {
        "refund_id": f"RF-{9000 + len(data.get('refunds', [])) + 13}",
        "order_id": order["order_id"],
        "amount": order["amount"],
        "currency": order.get("currency", "INR"),
        "status": "processing",
        "initiated_on": today.strftime("%Y-%m-%d"),
        "expected_by": (today + timedelta(days=5)).strftime("%Y-%m-%d"),
        "method": "original payment method",
        "reason": reason,
    }
    data.setdefault("refunds", []).append(refund)
    save_orders(data)
    return refund


def send_password_reset(email=None):
    """Send a password reset link. THIS CHANGES DATA."""
    data = load_orders()
    account = data.get("account", {})

    if not account:
        return {"error": "The account system is unavailable."}

    if email and email.lower() != account.get("email", "").lower():
        return {"error": "That email is not on this account."}

    stamp = datetime.now().isoformat(timespec="seconds")
    account["password_reset_sent_at"] = stamp
    data["account"] = account
    save_orders(data)
    return {"sent_to": account.get("email"), "sent_at": stamp,
            "expires_in_minutes": 30}


# ---- what the model is allowed to ask for ----
#
# "writes" marks the two that change data. Those are NOT run automatically --
# see gather_facts() below.

BACK_OFFICE = {
    "check_order_status": {
        "run": check_order_status, "writes": False,
        "declaration": types.FunctionDeclaration(
            name="check_order_status",
            description="Look up the status of an order. Omit order_id to "
                        "list the customer's recent orders.",
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "order_id": {"type": "string",
                                 "description": "e.g. OD-4471. Optional."},
                },
            },
        ),
    },
    "check_refund_status": {
        "run": check_refund_status, "writes": False,
        "declaration": types.FunctionDeclaration(
            name="check_refund_status",
            description="Look up a refund by refund id or by the order it "
                        "belongs to.",
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "order_id": {"type": "string", "description": "e.g. OD-4471"},
                    "refund_id": {"type": "string", "description": "e.g. RF-9012"},
                },
            },
        ),
    },
    "issue_refund": {
        "run": issue_refund, "writes": True,
        "declaration": types.FunctionDeclaration(
            name="issue_refund",
            description="Raise a refund against an order. Changes data, so it "
                        "needs a human to approve it.",
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "order_id": {"type": "string", "description": "e.g. OD-4471"},
                    "reason": {"type": "string",
                               "description": "Why the refund is being raised"},
                },
                "required": ["order_id"],
            },
        ),
    },
    "send_password_reset": {
        "run": send_password_reset, "writes": True,
        "declaration": types.FunctionDeclaration(
            name="send_password_reset",
            description="Email a password reset link. Changes data, so it "
                        "needs a human to approve it.",
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "email": {"type": "string",
                              "description": "The account email. Optional."},
                },
            },
        ),
    },
}

BACK_OFFICE_TOOL = types.Tool(
    function_declarations=[t["declaration"] for t in BACK_OFFICE.values()]
)


class AICoach:
    """Every call we make to the Gemini API lives in this class."""

    def __init__(self):
        """Create the Gemini client."""

        # The key is normally set in Step 2, but this class is used 19 cells
        # later. If Step 2 was skipped, or the kernel restarted, or the prompt
        # was dismissed, this asks again HERE -- at the moment the key is
        # actually needed -- instead of failing and making you scroll back up.
        api_key = get_gemini_api_key()

        if not api_key:
            raise ValueError(
                "No Gemini API key available, so Part 2 cannot run. "
                "Get a free key at https://aistudio.google.com/apikey and "
                "run Step 2 again."
            )

        self.client = genai.Client(api_key=api_key)
        self.last_redactions = []      # what the most recent call took out
        self.last_article = None       # the help article behind the last reply

        # You can change this through an environment variable, for example
        # os.environ["GEMINI_MODEL"] = "gemini-3.7-flash" for the newest model.
        self.model = os.getenv(
            "GEMINI_MODEL",
            "gemini-3.5-flash"
        )

    # ---------------- Helper functions ----------------

    def _clean(self, *texts):
        """Strip personal details out of everything about to be sent.

        A fresh Redactor per call, so one customer's details can never leak
        into another customer's placeholders, and the map cannot grow without
        bound over a long-running server.
        """
        redactor = Redactor()
        return redactor, [redactor.redact(text) for text in texts]


    # If our first-choice model is busy, try these next, in order. Free-tier
    # models get overloaded at peak times, and a demo should survive that.
    FALLBACK_MODELS = ["gemini-3.5-flash", "gemini-3.5-flash-lite"]

    # Errors worth waiting out: 503 = model busy, 429 = rate limited.
    RETRYABLE = ["503", "429", "UNAVAILABLE", "RESOURCE_EXHAUSTED"]
    # A malformed request is our fault, not the model's -- every other model
    # rejects it in exactly the same way, so falling back only doubles the
    # latency and the quota spent before we give up.
    FATAL = ["400", "INVALID_ARGUMENT", "401", "403", "PERMISSION_DENIED"]

    def _call_model(self, contents, config=None, max_attempts: int = 3):
        """One request to Gemini, with retries and model fallback.

        Every call goes through here -- plain text, structured JSON and tool
        calling alike. Tool calling in particular has a tighter free-tier
        limit than ordinary generation, so it needs this even more than the
        others do.
        """
        models_to_try = [self.model]
        for name in self.FALLBACK_MODELS:
            if name not in models_to_try:
                models_to_try.append(name)

        last_problem = "no attempt was made"

        for model_name in models_to_try:
            for attempt in range(max_attempts):
                try:
                    response = self.client.models.generate_content(
                        model=model_name,
                        contents=contents,
                        config=config,
                    )
                    self.last_model_used = model_name
                    return response

                except Exception as error:
                    last_problem = f"{type(error).__name__}: {error}"

                    if any(code in str(error) for code in self.RETRYABLE):
                        time.sleep(2 ** attempt)      # 1s, then 2s, then 4s
                        continue

                    if any(code in str(error) for code in self.FATAL):
                        raise ValueError(
                            f"Gemini rejected the request -> {last_problem}"
                        ) from error

                    break        # will not fix itself; try the next model

        raise ValueError(
            "Gemini could not be reached after trying "
            f"{', '.join(models_to_try)}. Last problem -> {last_problem}"
        )

    def _ask_model(
        self,
        prompt: str,
        schema: Optional[dict] = None,
        max_attempts: int = 3
    ) -> str:
        """Send one prompt to Gemini and return the reply as plain text.

        Pass a schema and the API guarantees the reply is JSON in that exact
        shape.
        """

        # Only build a config when we actually want structured output.
        config = None
        if schema is not None:
            config = types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=schema,
            )

        response = self._call_model(prompt, config, max_attempts)

        # response.text is None when the model returned no text at all -- for
        # example when a safety filter blocked the answer.
        text = (response.text or "").strip()

        if not text:
            raise ValueError(
                "The model returned no text. It may have been blocked by a "
                "safety filter, or you may have hit the free-tier rate limit."
            )

        return text

    def _ask_for_json(self, prompt: str, schema: dict) -> dict:
        """Ask for JSON whose shape the API itself guarantees."""
        return self._parse_json(self._ask_model(prompt, schema=schema))

    def _parse_json(self, text: str) -> dict:
        """Turn the model's reply into a Python dictionary.

        With a response schema this is now a safety net rather than the thing
        holding everything together: the API has already validated the shape.
        It still earns its place, because a fallback model that ignores the
        schema would land right back here.
        """

        text = text.strip()

        # Sometimes the reply is wrapped in a ```json ... ``` code fence.
        if text.startswith("```"):
            text = text.strip("`").strip()

            if text.lower().startswith("json"):
                text = text[4:].strip()

        try:
            return json.loads(text)

        except json.JSONDecodeError as e:

            print("\nCould not parse the model response as JSON.")
            print("Raw response:")
            print(text)

            raise ValueError(
                f"Invalid JSON returned by the model: {e}"
            )

    # ---------------- 1. Analyze customer message ----------------

    def analyze_customer_message(
        self,
        customer_message: str,
        conversation_history: Optional[List[Message]] = None
    ) -> dict:
        """Judge the latest customer message IN CONTEXT.

        Escalation is a property of a conversation, not of a sentence. Asked
        about one message on its own, the model cannot see that a customer
        opened politely and has been getting angrier for four turns -- which
        is the whole thing we care about. So we hand it the transcript and let
        it judge the trajectory directly, including a 0-100 frustration score.
        """

        # The whole conversation, ending with the message we are judging.
        turns = list(conversation_history or [])

        if not turns or turns[-1].text != customer_message:
            turns.append(Message(speaker="customer", text=customer_message))

        transcript = "\n".join(f"{turn.speaker}: {turn.text}" for turn in turns)
        redactor, (transcript,) = self._clean(transcript)

        prompt = f"""
You are an AI customer-support risk analyzer.

Read the WHOLE conversation below, then judge the customer as of their last
message. Earlier turns are context: they change what the last message means.

Conversation:
{transcript}

How to judge:
- A customer who opened politely and has grown angrier over several turns is
  at HIGHER risk than the same words would suggest on their own.
- A customer whose tone improved after a good agent reply is at LOWER risk
  than their angriest moment suggests.
- Repeating the same unresolved problem is itself a strong escalation signal,
  however politely it is phrased.
- If this is the first customer message, there is no trajectory yet, so the
  trend is "flat".

The shape of your answer is fixed by the response schema, so just fill it in.
"""

        # ANALYSIS_SCHEMA guarantees every field is present and that sentiment,
        # urgency and trend hold one of their allowed words.
        reading = self._ask_for_json(prompt, ANALYSIS_SCHEMA)

        # key_issue is written by the model and may quote a placeholder back
        # at us, so put the real values in before anyone reads it.
        reading["key_issue"] = redactor.restore(reading.get("key_issue", ""))
        self.last_redactions = redactor.log()

        # The score has to be a usable number whatever the model returns.
        try:
            reading["frustration"] = max(0, min(100, int(reading.get("frustration"))))
        except (TypeError, ValueError):
            # Fall back to the old word-to-number mapping rather than crash.
            reading["frustration"] = {
                "low": 25, "medium": 55, "high": 90
            }.get(reading.get("escalation_risk"), 35)

        if reading.get("trend") not in ("rising", "falling", "flat"):
            reading["trend"] = "flat"

        return reading

    # ---------------- 2. Evaluate agent response ----------------

    def evaluate_agent_response(
        self,
        customer_message: str,
        agent_message: str
    ) -> CoachingFeedback:

        redactor, (customer_message, agent_message) = self._clean(
            customer_message, agent_message)

        prompt = f"""
You are an AI customer-support coach. Score one agent reply.

Customer message:
{customer_message}

Agent reply:
{agent_message}

Score each dimension from 1 to 10 using these bands.

TONE -- is the wording professional, warm and appropriately serious?
  1-3    Curt, robotic or dismissive. Blames the customer, or reads like a
         form letter. No greeting and no courtesy.
  4-6    Polite but flat. Correct, with no warmth. Could have been sent to
         anybody about anything.
  7-10   Warm and professional. Sounds like a person who actually read the
         message and takes it seriously.

EMPATHY -- does the reply show the agent understood how the customer feels?
  1-3    Feelings ignored completely. Straight into process, or a bare
         demand for information.
  4-6    A token line ("sorry for the inconvenience") with nothing specific
         to this customer's situation.
  7-10   Names this customer's actual problem and what it has cost them,
         before moving on to the fix.

CLARITY -- will the customer know exactly what happens next?
  1-3    Vague or confusing. No next step, or jargon they cannot act on.
  4-6    Understandable, but the next step or the timeline is missing.
  7-10   One clear next step, who does it, and by when.

Be strict, and use the whole scale. Apply the bands literally:
- A reply with NO acknowledgement at all -- only a demand for information --
  must not score above 3 for empathy.
- A reply with a generic apology and nothing specific to this customer belongs
  in the 4-6 empathy band. Do not push it below 4 just for being generic.

Then give ONE concrete coaching tip: name the specific change to make, and why.

The shape of your answer is fixed by the response schema, so just fill it in.
"""

        result = self._ask_for_json(prompt, SCORECARD_SCHEMA)
        result["coaching_tip"] = redactor.restore(result.get("coaching_tip", ""))
        self.last_redactions = redactor.log()

        return CoachingFeedback(
            tone_score=int(result["tone_score"]),
            empathy_score=int(result["empathy_score"]),
            clarity_score=int(result["clarity_score"]),
            coaching_tip=result["coaching_tip"]
        )

    # ---------------- 2b. Look things up in the back office ----------------

    def gather_facts(
        self,
        customer_message: str,
        conversation_history: Optional[List[Message]] = None,
        allow_writes: bool = False,
        max_rounds: int = 3
    ) -> list:
        """Let the model query the order system before we draft a reply.

        This is a real function-calling loop: the model replies with the NAME
        of a function it wants, we run it here, hand back the result, and let
        it decide whether it needs anything else.

        allow_writes is off by default on purpose. A model that can silently
        issue refunds is a liability, so `issue_refund` and
        `send_password_reset` are recorded as REQUESTED and left unrun until
        a person approves them.
        """
        turns = list(conversation_history or [])
        if not turns or turns[-1].text != customer_message:
            turns.append(Message(speaker="customer", text=customer_message))
        transcript = "\n".join(f"{t.speaker}: {t.text}" for t in turns)
        redactor, (transcript,) = self._clean(transcript)

        prompt = f"""
You decide what to look up in the order system before a support agent replies.

Conversation:
{transcript}

Call whichever functions would let us answer this customer with real facts
rather than generalities. Rules:
- Only call a function that is clearly relevant to what they are asking.
- Never invent an order id. If the customer has not given one, call
  check_order_status with no arguments to see their recent orders first.
- If nothing needs looking up, reply with the single word NONE.
"""

        history = [types.Content(role="user", parts=[types.Part(text=prompt)])]
        performed = []

        for _ in range(max_rounds):
            try:
                response = self._call_model(
                    history,
                    types.GenerateContentConfig(
                        tools=[BACK_OFFICE_TOOL],
                        # We run the functions ourselves, so the SDK must not.
                        automatic_function_calling=
                            types.AutomaticFunctionCallingConfig(disable=True),
                    ),
                )
            except Exception as error:
                # A lookup failing must never stop us replying to the customer.
                performed.append({"name": "(lookup unavailable)", "args": {},
                                  "result": {"error": str(error)[:120]},
                                  "writes": False, "ran": False})
                break

            calls = response.function_calls or []
            if not calls:
                break                     # the model is done asking

            replies = []
            for call in calls:
                tool = BACK_OFFICE.get(call.name)

                # The model asked using placeholders, because that is all it
                # was given. Put the real ids back before the function runs --
                # the lookup happens inside our own process, where the real
                # values were never a secret.
                args = {key: redactor.restore(value) if isinstance(value, str)
                             else value
                        for key, value in (call.args or {}).items()}

                if tool is None:
                    result = {"error": f"No such function: {call.name}"}
                    ran = False
                elif tool["writes"] and not allow_writes:
                    # Requested, deliberately not run.
                    result = {"status": "awaiting approval",
                              "detail": "A person must approve this action "
                                        "before it is carried out."}
                    ran = False
                else:
                    try:
                        result = tool["run"](**args)
                        ran = True
                    except Exception as error:
                        result = {"error": f"{type(error).__name__}: {error}"}
                        ran = False

                performed.append({"name": call.name, "args": args,
                                  "result": result,
                                  "writes": bool(tool and tool["writes"]),
                                  "ran": ran})
                # The RESULT is full of real order ids, emails and amounts,
                # and it is about to be sent straight back to the model. Clean
                # it on the way out; the untouched copy stays in `performed`
                # for the agent to see.
                replies.append(types.Part.from_function_response(
                    name=call.name,
                    response={"result": json.loads(
                        redactor.redact(json.dumps(result)))}))

            history.append(response.candidates[0].content)
            # The API rejects role="tool" outright:
            #   Role 'tool' is not supported. Please use a valid role:
            #   SYSTEM, ... MODEL, USER.
            # Function results are handed back as a USER turn. Getting this
            # wrong meant round 1 worked and every round after it 400'd, so
            # the model could never chain two lookups together.
            history.append(types.Content(role="user", parts=replies))

        self.last_redactions = redactor.log()
        return performed

    # ---------------- 3. Suggest reply ----------------

    def suggest_reply(
        self,
        customer_message: str,
        conversation_history: Optional[List[Message]] = None,
        analysis: Optional[dict] = None,
        facts: Optional[list] = None
    ) -> str:

        # ---- 1. The conversation, written out exactly ONCE ----
        #
        # The history we are handed normally ends with the agent's own attempt
        # -- the very message we are being asked to improve on. Leaving it in
        # asks the model to reply to a conversation that has already been
        # replied to, so we trim any trailing agent turns off.
        #
        # This also fixes a real bug: the old version printed the customer
        # message once on its own AND again inside the history, so the model
        # saw it twice.
        turns = list(conversation_history or [])

        while turns and turns[-1].speaker == "agent":
            turns.pop()

        # Make sure the message we are replying to really is the last line.
        if not turns or turns[-1].text != customer_message:
            turns.append(Message(speaker="customer", text=customer_message))

        transcript = "\n".join(f"{turn.speaker}: {turn.text}" for turn in turns)

        # ---- 2. What we already worked out about this customer ----
        # analyze_customer_message() computed this seconds ago. Throwing it
        # away and making the model guess again is pure waste.
        if analysis:
            reading = (
                f"- sentiment: {analysis.get('sentiment', 'unknown')}\n"
                f"- urgency: {analysis.get('urgency', 'unknown')}\n"
                f"- main issue: {analysis.get('key_issue', 'not identified')}"
            )
        else:
            reading = "- no analysis was available for this turn"

        # ---- 3. The one piece of ground truth we can offer ----
        # Without this the model has NO facts, so "do not over-promise" is an
        # instruction it cannot actually follow -- all it can write is vague
        # filler. find_kb_article() comes from Step 14; if you jumped straight
        # to Part 2 without running it we carry on unarmed rather than crash.
        article = None
        try:
            article = find_kb_article(customer_message)
            if article is None and analysis and analysis.get("key_issue"):
                article = find_kb_article(analysis["key_issue"])
        except NameError:
            pass

        # Remember whether we had anything to ground this reply in, so the
        # rating it gets can be read against that. A suggestion written from
        # a real help article and one written from nothing are not the same
        # product, and lumping their scores together hides that.
        self.last_article = article

        if article:
            policy = (
                f'Our help article on "{article["topic"]}" says:\n'
                f'"""\n{article["article"]}\n"""\n\n'
                "Every timeline, step and condition in your reply must match "
                "this article exactly, but put them in your own words. Do not "
                "add any figure, deadline or promise that is not written above."
            )
        else:
            policy = (
                "NO help article matched this question, so you have no policy "
                "to quote.\n\n"
                "Do NOT invent a refund window, a delivery date, an amount, or "
                "any other commitment. Acknowledge the problem, say you are "
                "checking with the relevant team, and promise to come back."
            )

        # ---- 4. Anything we actually looked up in the order system ----
        # These are real records, not the model's memory, so they outrank
        # everything else in the prompt.
        if facts:
            lines = []
            for fact in facts:
                if fact.get("ran"):
                    lines.append(f"- {fact['name']}({json.dumps(fact['args'])})"
                                 f" returned: {json.dumps(fact['result'])}")
                else:
                    lines.append(f"- {fact['name']} was NOT carried out: "
                                 f"{json.dumps(fact['result'])}")
            lookups = (
                "What our order system says (these are real records — use them "
                "in preference to anything else, and quote the exact ids, dates "
                "and amounts):\n" + "\n".join(lines) +
                "\n\nIf an action was not carried out, do not tell the customer "
                "it was done. Say it is being arranged."
            )
        else:
            lookups = "We did not look anything up in the order system for this turn."

        # Everything above is about to leave the machine, so it all gets
        # cleaned -- the transcript, our own analysis, the order records and
        # the help article alike.
        redactor, (transcript, reading, lookups, policy) = self._clean(
            transcript, reading, lookups, policy)

        prompt = f"""
You are an expert customer-support agent. Write the agent's next reply.

Conversation so far (you are replying to the last line):
{transcript}

What our analysis says about this customer right now:
{reading}

{lookups}

{policy}

Requirements:
- Acknowledge the concern, and match your tone to the sentiment and urgency above.
- Show empathy without being sugary.
- State the next concrete step.
- Never promise anything the help article does not support.
- Write the WHOLE reply in clear, simple English, even when the customer wrote
  in Hinglish. Do not mix languages within a sentence.
- Keep it under 90 words.
"""

        # This one returns prose, so there is no JSON shape to guarantee. The
        # schema still earns its keep: a single "reply" field makes it
        # impossible to prepend "Here is a reply:" or wrap the answer in
        # commentary, which used to be an instruction the model could ignore.
        reply = self._ask_for_json(prompt, REPLY_SCHEMA)["reply"].strip()
        self.last_redactions = redactor.log()

        # The customer is entitled to see their own details, so the real
        # values go back in before the reply is shown to anyone.
        return redactor.restore(reply)
